server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://admin:1234@localhost:8082/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: gateway