server:
  port: 8001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://admin:1234@localhost:8002/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true

# key-manager
user:
  access:
    key:
      id: Af0QCnBKw2gcfqGNxBtN
key-manager:
  api:
    key: 2SxwmBzUfnqJaA2A

# key-manager-secret
secret:
  access:
    key: fg7cdQvIPJUDUC9p
  key:
    jwt: e497c0cfde874a1ea54a864caefecd28
    client:
      encoding: f8030279a1eb4977a7e1d141c28738ca

#logging:
#  level:
#    root: debug